### ISSUE TITLE
Crash when querying game cards not in my collection 

### ISSUE THREAD

**Issue by amselem** [przepinski/bgguwp#7]
I'm experiencing app crashes when entering game cards not in my collection (entering from home section).
The crash happens a second after entering the card, it looks like just when the app is checking if the game is in my collection (so the "+ Add" button turns into an "Edit" button).
It crashes with all games not in my collection (eg: Food Chain Magnate, Pandemic Iberia) and with some games in my collection too (Alien Frontiers, Fief). It doesn't crash with most games in my collection (Core Worlds, Cyclades, Earth Reborn)

**Comment by rzepinskip** [comment]
Main crash issue is fixed with bd040e695c3befec761c1e5f9b90eac4347a7938. I was referencing null value, because I did not test it thoroughly. 
Loading rules link crash fixed in fd4e96a0bedff60bbcc438fcf348d117a483fb76.
