### ISSUE TITLE
Specific version/edition is not shown in the game card

### ISSUE THREAD

**Issue by amselem** [przepinski/bgguwp#9]
I the game colletion view list, it shows correctly the specific edition (title+picture) that I've chosen in BGG (eg: Gloria a Roma, La Furia de Drácula)
However when entering the game card it shows the english version title (eg: Glory to Rome, Fury of Dracula) and picture.

**Comment by rzepinskip** [comment]
It is connected with BoardGameGeek API data. There is no easy way to fix it.

**Comment by rzepinskip** [comment]
I found a way - different collection items navigate to different board game pages since 373ea847c8d3b3dc39aa62c74e956d4d4329c215.

**Comment by amselem** [comment]
Great! But it's only working with the game title. Could you make it work with the game picture?
